// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/amorindev/go-tmpl/pkg/app/auth-methods/port (interfaces: AuthMethodSrv)
//
// Generated by this command:
//
//	mockgen -destination mocks/app/auth-methods/mock_auth_method_srv.go -package auth_method github.com/amorindev/go-tmpl/pkg/app/auth-methods/port AuthMethodSrv
//

// Package auth_method is a generated GoMock package.
package auth_method

import (
	context "context"
	reflect "reflect"

	domain "github.com/amorindev/go-tmpl/pkg/app/session/domain"
	domain0 "github.com/amorindev/go-tmpl/pkg/app/users/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthMethodSrv is a mock of AuthMethodSrv interface.
type MockAuthMethodSrv struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMethodSrvMockRecorder
	isgomock struct{}
}

// MockAuthMethodSrvMockRecorder is the mock recorder for MockAuthMethodSrv.
type MockAuthMethodSrvMockRecorder struct {
	mock *MockAuthMethodSrv
}

// NewMockAuthMethodSrv creates a new mock instance.
func NewMockAuthMethodSrv(ctrl *gomock.Controller) *MockAuthMethodSrv {
	mock := &MockAuthMethodSrv{ctrl: ctrl}
	mock.recorder = &MockAuthMethodSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthMethodSrv) EXPECT() *MockAuthMethodSrvMockRecorder {
	return m.recorder
}

// SignIn mocks base method.
func (m *MockAuthMethodSrv) SignIn(ctx context.Context, email, password string, rememberMe bool) (*domain0.User, *domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", ctx, email, password, rememberMe)
	ret0, _ := ret[0].(*domain0.User)
	ret1, _ := ret[1].(*domain.Session)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SignIn indicates an expected call of SignIn.
func (mr *MockAuthMethodSrvMockRecorder) SignIn(ctx, email, password, rememberMe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockAuthMethodSrv)(nil).SignIn), ctx, email, password, rememberMe)
}

// SignUp mocks base method.
func (m *MockAuthMethodSrv) SignUp(ctx context.Context, user *domain0.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignUp indicates an expected call of SignUp.
func (mr *MockAuthMethodSrvMockRecorder) SignUp(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockAuthMethodSrv)(nil).SignUp), ctx, user)
}
