// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/amorindev/go-tmpl/pkg/app/users/port (interfaces: UserSrv)
//
// Generated by this command:
//
//	mockgen -destination mocks/app/users/mock_user_srv.go -package users github.com/amorindev/go-tmpl/pkg/app/users/port UserSrv
//

// Package users is a generated GoMock package.
package users

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserSrv is a mock of UserSrv interface.
type MockUserSrv struct {
	ctrl     *gomock.Controller
	recorder *MockUserSrvMockRecorder
	isgomock struct{}
}

// MockUserSrvMockRecorder is the mock recorder for MockUserSrv.
type MockUserSrvMockRecorder struct {
	mock *MockUserSrv
}

// NewMockUserSrv creates a new mock instance.
func NewMockUserSrv(ctrl *gomock.Controller) *MockUserSrv {
	mock := &MockUserSrv{ctrl: ctrl}
	mock.recorder = &MockUserSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSrv) EXPECT() *MockUserSrvMockRecorder {
	return m.recorder
}

// UploadAvatar mocks base method.
func (m *MockUserSrv) UploadAvatar(ctx context.Context, path string, file io.Reader, userID, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, path, file, userID, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockUserSrvMockRecorder) UploadAvatar(ctx, path, file, userID, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockUserSrv)(nil).UploadAvatar), ctx, path, file, userID, contentType)
}
