// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/amorindev/go-tmpl/pkg/app/users/port (interfaces: UserFileStg)
//
// Generated by this command:
//
//	mockgen -destination mocks/app/users/mock_user_file_stg.go -package users github.com/amorindev/go-tmpl/pkg/app/users/port UserFileStg
//

// Package users is a generated GoMock package.
package users

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserFileStg is a mock of UserFileStg interface.
type MockUserFileStg struct {
	ctrl     *gomock.Controller
	recorder *MockUserFileStgMockRecorder
	isgomock struct{}
}

// MockUserFileStgMockRecorder is the mock recorder for MockUserFileStg.
type MockUserFileStgMockRecorder struct {
	mock *MockUserFileStg
}

// NewMockUserFileStg creates a new mock instance.
func NewMockUserFileStg(ctrl *gomock.Controller) *MockUserFileStg {
	mock := &MockUserFileStg{ctrl: ctrl}
	mock.recorder = &MockUserFileStgMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFileStg) EXPECT() *MockUserFileStgMockRecorder {
	return m.recorder
}

// GetImage mocks base method.
func (m *MockUserFileStg) GetImage(ctx context.Context, imgPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, imgPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockUserFileStgMockRecorder) GetImage(ctx, imgPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockUserFileStg)(nil).GetImage), ctx, imgPath)
}

// UploadImage mocks base method.
func (m *MockUserFileStg) UploadImage(ctx context.Context, imgPath string, file io.Reader, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, imgPath, file, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockUserFileStgMockRecorder) UploadImage(ctx, imgPath, file, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockUserFileStg)(nil).UploadImage), ctx, imgPath, file, contentType)
}
