// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/amorindev/go-tmpl/pkg/app/session/port (interfaces: SessionRepo)
//
// Generated by this command:
//
//	mockgen -destination mocks/app/sessions/mock_session_repo.go -package sessions github.com/amorindev/go-tmpl/pkg/app/session/port SessionRepo
//

// Package sessions is a generated GoMock package.
package sessions

import (
	context "context"
	reflect "reflect"

	domain "github.com/amorindev/go-tmpl/pkg/app/session/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepo is a mock of SessionRepo interface.
type MockSessionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepoMockRecorder
	isgomock struct{}
}

// MockSessionRepoMockRecorder is the mock recorder for MockSessionRepo.
type MockSessionRepoMockRecorder struct {
	mock *MockSessionRepo
}

// NewMockSessionRepo creates a new mock instance.
func NewMockSessionRepo(ctrl *gomock.Controller) *MockSessionRepo {
	mock := &MockSessionRepo{ctrl: ctrl}
	mock.recorder = &MockSessionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepo) EXPECT() *MockSessionRepoMockRecorder {
	return m.recorder
}

// DeleteByRTokenID mocks base method.
func (m *MockSessionRepo) DeleteByRTokenID(ctx context.Context, rTokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByRTokenID", ctx, rTokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByRTokenID indicates an expected call of DeleteByRTokenID.
func (mr *MockSessionRepoMockRecorder) DeleteByRTokenID(ctx, rTokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByRTokenID", reflect.TypeOf((*MockSessionRepo)(nil).DeleteByRTokenID), ctx, rTokenID)
}

// Insert mocks base method.
func (m *MockSessionRepo) Insert(ctx context.Context, session *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockSessionRepoMockRecorder) Insert(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockSessionRepo)(nil).Insert), ctx, session)
}
