// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/amorindev/go-tmpl/pkg/app/session/port (interfaces: SessionSrv)
//
// Generated by this command:
//
//	mockgen -destination mocks/app/sessions/mock_session_srv.go -package sessions github.com/amorindev/go-tmpl/pkg/app/session/port SessionSrv
//

// Package sessions is a generated GoMock package.
package sessions

import (
	context "context"
	reflect "reflect"

	domain "github.com/amorindev/go-tmpl/pkg/app/session/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionSrv is a mock of SessionSrv interface.
type MockSessionSrv struct {
	ctrl     *gomock.Controller
	recorder *MockSessionSrvMockRecorder
	isgomock struct{}
}

// MockSessionSrvMockRecorder is the mock recorder for MockSessionSrv.
type MockSessionSrvMockRecorder struct {
	mock *MockSessionSrv
}

// NewMockSessionSrv creates a new mock instance.
func NewMockSessionSrv(ctrl *gomock.Controller) *MockSessionSrv {
	mock := &MockSessionSrv{ctrl: ctrl}
	mock.recorder = &MockSessionSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionSrv) EXPECT() *MockSessionSrvMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionSrv) Create(ctx context.Context, session *domain.Session, roles []string, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session, roles, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionSrvMockRecorder) Create(ctx, session, roles, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionSrv)(nil).Create), ctx, session, roles, email)
}

// DeleteByRTokenID mocks base method.
func (m *MockSessionSrv) DeleteByRTokenID(ctx context.Context, rTokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByRTokenID", ctx, rTokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByRTokenID indicates an expected call of DeleteByRTokenID.
func (mr *MockSessionSrvMockRecorder) DeleteByRTokenID(ctx, rTokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByRTokenID", reflect.TypeOf((*MockSessionSrv)(nil).DeleteByRTokenID), ctx, rTokenID)
}
