// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/amorindev/go-tmpl/internal/tokens/port (interfaces: TokenSrv)
//
// Generated by this command:
//
//	mockgen -destination mocks/in_ter_nal/token/mock_token_srv.go -package tokens github.com/amorindev/go-tmpl/internal/tokens/port TokenSrv
//

// Package tokens is a generated GoMock package.
package tokens

import (
	reflect "reflect"

	claim "github.com/amorindev/go-tmpl/internal/tokens/claim"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenSrv is a mock of TokenSrv interface.
type MockTokenSrv struct {
	ctrl     *gomock.Controller
	recorder *MockTokenSrvMockRecorder
	isgomock struct{}
}

// MockTokenSrvMockRecorder is the mock recorder for MockTokenSrv.
type MockTokenSrvMockRecorder struct {
	mock *MockTokenSrv
}

// NewMockTokenSrv creates a new mock instance.
func NewMockTokenSrv(ctrl *gomock.Controller) *MockTokenSrv {
	mock := &MockTokenSrv{ctrl: ctrl}
	mock.recorder = &MockTokenSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenSrv) EXPECT() *MockTokenSrvMockRecorder {
	return m.recorder
}

// CreateAccessToken mocks base method.
func (m *MockTokenSrv) CreateAccessToken(userID, email string, roles []string) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessToken", userID, email, roles)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateAccessToken indicates an expected call of CreateAccessToken.
func (mr *MockTokenSrvMockRecorder) CreateAccessToken(userID, email, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessToken", reflect.TypeOf((*MockTokenSrv)(nil).CreateAccessToken), userID, email, roles)
}

// CreateRefreshToken mocks base method.
func (m *MockTokenSrv) CreateRefreshToken(userID string, rememberMe bool) (string, string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", userID, rememberMe)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockTokenSrvMockRecorder) CreateRefreshToken(userID, rememberMe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockTokenSrv)(nil).CreateRefreshToken), userID, rememberMe)
}

// ParseAccessToken mocks base method.
func (m *MockTokenSrv) ParseAccessToken(tokenStr string) (*claim.AccessTokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAccessToken", tokenStr)
	ret0, _ := ret[0].(*claim.AccessTokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAccessToken indicates an expected call of ParseAccessToken.
func (mr *MockTokenSrvMockRecorder) ParseAccessToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAccessToken", reflect.TypeOf((*MockTokenSrv)(nil).ParseAccessToken), tokenStr)
}

// ParseRefreshToken mocks base method.
func (m *MockTokenSrv) ParseRefreshToken(tokenStr string) (*claim.RefreshTokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRefreshToken", tokenStr)
	ret0, _ := ret[0].(*claim.RefreshTokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseRefreshToken indicates an expected call of ParseRefreshToken.
func (mr *MockTokenSrvMockRecorder) ParseRefreshToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRefreshToken", reflect.TypeOf((*MockTokenSrv)(nil).ParseRefreshToken), tokenStr)
}
